export const DEFAULT_PREFIX = ".";
export const DEV_PREFIX = "rack ";
export const DEV_IDS = ["880070472434339880"];
export const DEV_LOG_CHANNEL_ID = "1490834335375298666";
export const CURRENCY_SYMBOL = "⚡";
export const CURRENCY_NAME = "raqs";

export const DAILY_AMOUNT = 1000;
export const DAILY_COOLDOWN = 24 * 60 * 60 * 1000;
export const WORK_MIN = 250;
export const WORK_MAX = 750;
export const WORK_COOLDOWN = 60 * 60 * 1000;
export const WANTED_WORK_MULTIPLIER = 0.6;
export const ROB_COOLDOWN = 2 * 60 * 60 * 1000;
export const ROB_SUCCESS_RATE = 0.5;
export const ROB_FINE_PERCENT = 0.25;
export const ROB_MIN_BAL = 500;
export const BAIL_BASE_COST = 6000;
export const BAIL_COST_PER_MINUTE = 12;

export const HEIST_MIN_PLAYERS = 2;
export const HEIST_JOIN_WINDOW = 30 * 1000;
export const HEIST_MIN_BET = 1000;
export const HEIST_MAX_BET = 100000;
export const HEIST_BASE_COOLDOWN = 25 * 60 * 1000;
export const WANTED_DURATION = 24 * 60 * 60 * 1000;

export const CASINO_MIN_BET = 100;
export const CASINO_MAX_BET = 50000;

export const RANK_THRESHOLDS = {
	Regular: 0,
	"High Roller": 100000,
	VIP: 1000000,
	Whale: 10000000,
};
export const RANK_MAX_BETS = {
	Regular: 50000,
	"High Roller": 200000,
	VIP: 1000000,
	Whale: 5000000,
};

export const TAX_RATE = 0.05;
export const TAX_THRESHOLD = 5000;
export const EVADE_FINE_RATE = 0.25;

export const BLACKMARKET_LISTING_FEE = 50;
export const BLACKMARKET_MAX_LISTINGS = 5;
export const BLACKMARKET_EXPIRY = 24 * 60 * 60 * 1000;

export const COLOR_PRIMARY = 0xa1cf3a;
export const COLOR_SUCCESS = 0x2dc653;
export const COLOR_ERROR = 0xff6b6b;
export const COLOR_WARNING = 0xffb703;
export const COLOR_INFO = 0xa1cf3a;
export const COLOR_ECONOMY = 0xffd700;

export const FOOTER = "Racket Economy Bot";
export const FOOTER_ICON = null;

export default {
	DEFAULT_PREFIX,
	DEV_PREFIX,
	DEV_IDS,
	DEV_LOG_CHANNEL_ID,
	CURRENCY_SYMBOL,
	CURRENCY_NAME,
	DAILY_AMOUNT,
	DAILY_COOLDOWN,
	WORK_MIN,
	WORK_MAX,
	WORK_COOLDOWN,
	WANTED_WORK_MULTIPLIER,
	ROB_COOLDOWN,
	ROB_SUCCESS_RATE,
	ROB_FINE_PERCENT,
	ROB_MIN_BAL,
	BAIL_BASE_COST,
	BAIL_COST_PER_MINUTE,
	HEIST_MIN_PLAYERS,
	HEIST_JOIN_WINDOW,
	HEIST_MIN_BET,
	HEIST_MAX_BET,
	HEIST_BASE_COOLDOWN,
	WANTED_DURATION,
	CASINO_MIN_BET,
	CASINO_MAX_BET,
	RANK_THRESHOLDS,
	RANK_MAX_BETS,
	TAX_RATE,
	TAX_THRESHOLD,
	EVADE_FINE_RATE,
	BLACKMARKET_LISTING_FEE,
	BLACKMARKET_MAX_LISTINGS,
	BLACKMARKET_EXPIRY,
	COLOR_PRIMARY,
	COLOR_SUCCESS,
	COLOR_ERROR,
	COLOR_WARNING,
	COLOR_INFO,
	COLOR_ECONOMY,
	FOOTER,
	FOOTER_ICON,
};
